export const HONEY_PROGRAM_ID = '6ujVJiHnyqaTBHzwwfySzTDX5EPFgmXqnibuMp3Hun1w';
export const HONEY_MARKET_ID = 'EYFjQT4zt6S4swvVVDVX4tkTKcFz339HCwT5NvFqHHW4'
export const OPEN_POSITIONS = "Open positions";
export const NEW_POSITIONS = "New position";
export const TYPE_OPEN = "open";
export const TYPE_CLOSED = "closed";
export const TYPE_PRIMARY = "primary";
export const TYPE_SECONDARY = "secondary";
export const TYPE_ZERO = 0;
export const TYPE_ONE = 1;
export const TYPE_BORROW = 'borrow';
export const TYPE_REPAY = 'repay';
export const LTV = 0.6;